customer-docs/doc-versions.yml
customer-docs/quickstart.md
customer-docs/user-manual.md

Correcting the path for images directory.

correcting the image paths

---

customer-docs/doc-versions.yml

@satish-sanjeev @brockn @afoerster

change doc version to include weight and archive

---

customer-docs/doc-versions.yml
customer-docs/quickstart.md

Update image path for customer docs site visibility

---

customer-docs/user-manual.md

Fix formatting for yaml in the user manual.

Fix formatting for yaml in the user manual.

---

customer-docs/quickstart.md

Change-Id: I7666664facd902fc7749c05ec06aeebe70eace15

Minor fixes to quickstart

---

customer-docs/doc-versions.yml

Change-Id: I2911d05ada539af2020d6ae02d651c620eb45434

Release doc typos

---

src/main/scala/io/phdata/streamliner/configuration/parser/JDBCParser.scala

Make our schema matching a little more flexible based on feedback troy had on Oracle and MSSQL.
Change-Id: Iba9514088f4133300654edef036355bcf9b1d99d

Make our schema matching a little more flexible

---

customer-docs/user-manual.md

Change-Id: I7527f8df24fe19150a2fd3129d2acec7ac496597

PIP-293 - Clarify password on the CLI vs passwordFile

---

src/main/resources/templates/snowflake/shared/copy-into.ssp
src/main/resources/templates/snowflake/shared/create-table.ssp
src/main/resources/templates/snowflake/snowflake-aws-dms-merge/create-report-table.sql.ssp
src/main/resources/templates/snowflake/snowflake-aws-dms-merge/create-snowpipe.sql.ssp
src/main/resources/templates/snowflake/snowflake-aws-dms-merge/create-staging-table.sql.ssp
src/main/resources/templates/snowflake/snowflake-snowpipe-append-with-qa/copy-into.sql.ssp
src/main/resources/templates/snowflake/snowflake-snowpipe-append/copy-into.sql.ssp
src/main/scala/io/phdata/streamliner/configuration/mapper/HadoopTableMapper.scala
src/main/scala/io/phdata/streamliner/configuration/mapper/SnowflakeTableMapper.scala
src/main/scala/io/phdata/streamliner/configuration/mapper/TableMapper.scala
src/main/scala/io/phdata/streamliner/configuration/package.scala

Change-Id: Idc3ff980a5dce932fc295f5c87ccfae513a49e40

STREAM-8 columns with special characters with snowflake

---

src/main/scala/io/phdata/streamliner/configuration/mapper/SnowflakeTableMapper.scala

If a source system table does not have primary keys defined look for a unique index and use those column definitions

Added fallback primary key parsing

---

customer-docs/changelog.md

Change-Id: I672d3d2b62588b0e70ac5ed5b7ee9a14b731798a

Move changelog to customer-docs and update with all release info

---

build.sbt
src/test/java/schemacrawler/crawl/MySQLTestContainerTest.java
src/test/resources/conf/ingest-configuration.yml

* Added mysql testcontainer.
* added junit to test streamliner schema command which generates `streamliner-configuration.yml`.
* added junit to test streamliner script command using `streamliner-configuration.yml` and generates all `.sql` files

Simple Junit to test streamliner schema and script command.

---

src/main/java/io/phdata/streamliner/schemadefiner/ConfigBuilder/SchemaCommand.java
src/main/java/io/phdata/streamliner/schemadefiner/GlueCrawler.java
src/main/java/io/phdata/streamliner/schemadefiner/JdbcCrawler.java
src/main/java/io/phdata/streamliner/schemadefiner/Mapper/HadoopMapper.java
src/main/java/io/phdata/streamliner/schemadefiner/Mapper/SnowflakeMapper.java
src/main/java/io/phdata/streamliner/schemadefiner/SchemaDefiner.java
src/main/java/io/phdata/streamliner/schemadefiner/StreamlinerConfigReader.java
src/main/java/io/phdata/streamliner/schemadefiner/model/ColumnDefinition.java
src/main/java/io/phdata/streamliner/schemadefiner/model/Configuration.java
src/main/java/io/phdata/streamliner/schemadefiner/model/Database.java
src/main/java/io/phdata/streamliner/schemadefiner/model/Destination.java
src/main/java/io/phdata/streamliner/schemadefiner/model/FileFormat.java
src/main/java/io/phdata/streamliner/schemadefiner/model/IngestConfigFileFormat.java
src/main/java/io/phdata/streamliner/schemadefiner/model/Options.java
src/main/java/io/phdata/streamliner/schemadefiner/model/Source.java
src/main/java/io/phdata/streamliner/schemadefiner/model/TableDefinition.java
src/main/java/io/phdata/streamliner/schemadefiner/model/UserDefinedTable.java
src/main/java/io/phdata/streamliner/schemadefiner/util/StreamlinerUtil.java
src/main/java/schemacrawler/crawl/SchemaDefinerHelper.java
src/main/java/schemacrawler/crawl/StreamlinerSchemaCrawler.java
src/test/java/io/phdata/streamliner/schemadefiner/MySQLTestContainerTest.java
src/test/resources/conf/ingest-configuration-glue.yml

* created  SchemaDefiner interface and all implementation classes.
* implemented JdbcCrawler and StreamlinerConfigReader retrieveSchema()
* added Junit to test JdbcCrawler and StreamlinerConfigReader retrieveSchema()

STREAM-14  SchemaDefiner interface and implementations

---

build.sbt
src/main/java/io/phdata/streamliner/schemadefiner/StreamlinerConfigReader.java
src/main/java/io/phdata/streamliner/schemadefiner/model/ColumnDiff.java
src/main/java/io/phdata/streamliner/schemadefiner/model/ConfigurationDiff.java
src/main/java/io/phdata/streamliner/schemadefiner/model/TableDiff.java
src/main/java/io/phdata/streamliner/schemadefiner/util/StreamlinerUtil.java
src/test/java/io/phdata/streamliner/schemadefiner/MySQLTestContainerTest.java

* Added model class ConfigurationDiff, TableDiff, ColumnDiff
* Added junit to serialize and de-serialize ConfigurationDiff.
* Removed snakeyaml, added jackson to parse Yaml. Now order of parameters are preserved in yaml file. Junit still refer snakeyaml that will be removed.

STREAM-15 Create Diff Definition classes

---

src/main/java/io/phdata/streamliner/schemadefiner/ConfigBuilder/DiffGenerator.java
src/main/java/io/phdata/streamliner/schemadefiner/model/TableDiff.java
src/main/java/io/phdata/streamliner/schemadefiner/util/StreamlinerUtil.java
src/test/java/io/phdata/streamliner/schemadefiner/DiffGeneratorTest.java
src/test/java/io/phdata/streamliner/schemadefiner/MySQLTestContainerTest.java
src/test/resources/conf/ingest-configuration.yml
src/test/resources/configDiff/addAllColumn/currConfig.yml
src/test/resources/configDiff/addColumn/currConfig.yml
src/test/resources/configDiff/addColumn/prevConfig.yml
src/test/resources/configDiff/addTable/currConfig.yml
src/test/resources/configDiff/addTable/prevConfig.yml
src/test/resources/configDiff/changeColumn/currConfig.yml
src/test/resources/configDiff/changeColumn/prevConfig.yml
src/test/resources/configDiff/deleteColumn/currConfig.yml
src/test/resources/configDiff/deleteColumn/prevConfig.yml
src/test/resources/configDiff/deleteTable/currConfig.yml
src/test/resources/configDiff/deleteTable/prevConfig.yml
src/test/resources/configDiff/hybridChanges/currConfig.yml
src/test/resources/configDiff/hybridChanges/prevConfig.yml

* Implemented configurationDiff generator provided previous and current configs.
* added Junit to test configDiff generator for below cases
1. If previous config is empty, every column is ADD
2. new column added
3. old column deleted
4. change in column, eg: changing length on VARCHAR
* added prevConfig and currConfig for each use case.

STREAM-17 Implement Column Diff Creation

---

src/main/java/io/phdata/streamliner/schemadefiner/ConfigBuilder/SchemaCommand.java
src/main/java/io/phdata/streamliner/schemadefiner/ConfigBuilder/SchemaEvolutionCommand.java
src/main/java/io/phdata/streamliner/schemadefiner/util/StreamlinerUtil.java
src/main/scala/io/phdata/streamliner/App.scala
src/main/scala/io/phdata/streamliner/Cli.scala

* updated Cli.scala to support schema-evolution

STREAM-18 Create schema-evolution command

---

src/main/java/io/phdata/streamliner/schemadefiner/ConfigBuilder/SchemaCommand.java
src/main/java/io/phdata/streamliner/schemadefiner/ConfigBuilder/SchemaEvolution.java
src/main/java/io/phdata/streamliner/schemadefiner/ConfigBuilder/ScriptCommand.java
src/main/java/io/phdata/streamliner/schemadefiner/SchemaDefiner.java
src/main/java/io/phdata/streamliner/schemadefiner/StreamlinerConfigReader.java
src/main/java/io/phdata/streamliner/schemadefiner/util/StreamlinerUtil.java
src/main/scala/io/phdata/streamliner/App.scala
src/main/scala/io/phdata/streamliner/Cli.scala
src/test/java/io/phdata/streamliner/schemadefiner/DiffGeneratorTest.java
src/test/java/io/phdata/streamliner/schemadefiner/MySQLTestContainerTest.java
src/test/java/io/phdata/streamliner/schemadefiner/ScriptCommandTest.java

* removed schema-evolution command
* modified schema command.
1. removed --output-path
2. added --output-file
3. added -- previous-output-file
4. added -- diff-output-file
* added junit to test modified schema command

STREAM-23 Command and path restructure

---

src/main/java/io/phdata/streamliner/schemadefiner/ConfigBuilder/SchemaCommand.java
src/main/java/io/phdata/streamliner/schemadefiner/util/StreamlinerUtil.java
src/test/java/io/phdata/streamliner/schemadefiner/MySQLTestContainerTest.java

* added else block for unknown source type, destination type and table type
* updated logic to check output-file is a directory
* updated junits

STREAM-24 Potential bug handling

---

src/main/java/io/phdata/streamliner/schemadefiner/JdbcCrawler.java
src/main/java/io/phdata/streamliner/schemadefiner/model/GlueCatalog.java
src/main/java/io/phdata/streamliner/schemadefiner/model/Jdbc.java
src/main/java/io/phdata/streamliner/schemadefiner/util/StreamlinerUtil.java
src/main/java/schemacrawler/crawl/StreamlinerSchemaCrawler.java
src/test/java/io/phdata/streamliner/schemadefiner/MySQLTestContainerTest.java
src/test/java/schemacrawler/crawl/StreamlinerSchemaCrawlerTest.java
src/test/resources/conf/ingest-configuration-tableWhitelisting.yml

* introduced "tables" parameter for whitelist and userDefinedTable is for metadata override
* added junit to test table whitelist

STREAM-37 Implement Table whitelisting

---

customer-docs/schema-evolution.md

Removed the following to display the headings of the document to right side of the screen to inline with other pages.
- [Introduction](#introduction)
- [Order of Operations](#order-of-operations)
- [Commands](#commands)

changes made to schema-evalution.md

---

src/main/java/io/phdata/streamliner/schemadefiner/configbuilder/SchemaCommand.java
src/test/java/io/phdata/streamliner/schemadefiner/MySQLTestContainerTest.java

Below logic is implemented: 
if(file.exists){
if(file.isDirectory) -> throw exception
} else {
createNewFile 
}

STREAM-23 Schema command bug fix. Create config files if does not exists

---

src/main/resources/templates/snowflake/shared/drop-stage-qa-task.ssp

* missed to replace old scala model class in drop-stage-qa-task.ssp

Template bug fix.

---

src/main/resources/templates/snowflake/Makefile.schema.ssp
src/main/resources/templates/snowflake/snowflake-schema-evolution/Makefile.ssp

* updated correct target name Makefile.schema.ssp
* updated correct template name in snowflake-schema-evolution/Makefile.ssp

STREAM-67 Updating correct target name and log message.

---

src/main/java/io/phdata/streamliner/schemadefiner/configbuilder/GenerateStateCommand.java

* during state file generation sort tables and columns similar to schema file generation.
* assign precision and scale from source schema file similar to datatype.

STREAM-77 Updates to MDT state file

---

src/main/java/io/phdata/streamliner/schemadefiner/model/Destination.java
src/main/java/io/phdata/streamliner/schemadefiner/model/HadoopTable.java
src/main/java/io/phdata/streamliner/schemadefiner/model/SnowflakeTable.java
src/main/java/io/phdata/streamliner/schemadefiner/model/Source.java
src/main/java/io/phdata/streamliner/schemadefiner/model/TableDefinition.java
src/main/java/io/phdata/streamliner/schemadefiner/model/UserDefinedTable.java
src/test/java/io/phdata/streamliner/schemadefiner/DiffGeneratorTest.java
src/test/java/io/phdata/streamliner/schemadefiner/ScriptCommandTest.java

* Removed hardcoded type value in SnowflakeTable and HadoopTable.
* added visible=true in TableDefinition JsonTypeInfo that retains the type value
* added Junit test case for table delete use case for script generation

STREAM-79 Fix bug while jackson serialization /de-serialization

---

src/main/java/io/phdata/streamliner/schemadefiner/JdbcCrawler.java
src/main/java/io/phdata/streamliner/schemadefiner/configbuilder/SchemaCommand.java
src/main/java/io/phdata/streamliner/schemadefiner/util/StreamlinerUtil.java
src/test/resources/conf/ingest-configuration-tableWhitelisting.yml
src/test/resources/conf/ingest-configuration.yml

STREAM-90 - Fix streamliner 4.x bug where no tables were found

---

customer-docs/quickstart.md
customer-docs/schema-evolution.md
src/test/resources/results/scriptCommand/testScriptCommandForSchemaEvolution_Create_Table/Department/Makefile
src/test/resources/templates/snowflake/snowflake-snowpipe-append/Makefile.ssp

* update streamliner exception process
* update streamliner commands in quickstart and schema evolution page.

STREAM-88 Update Streamliner docs and Makefile

---

customer-docs/changelog.md
customer-docs/doc-versions.yml
customer-docs/known-issues.md

changes for deleting artifactory references in the docs and adding a known issues page providing the instructions for migrating to cloudsmith

Document changes required for cloudsmith migration

---

src/main/java/io/phdata/streamliner/schemadefiner/util/StreamlinerUtil.java

* User connecting to MSSQL are facing issue. This is because schemas are matched only based on name. Now we have included schema matching based on full name also.

STREAM-109 Change schema matching logic

---

customer-docs/changelog.md
customer-docs/doc-versions.yml

* also updated doc-version for streamliner 4.4

STREAM-110 updated changelog and doc-version for streamliner 5.5.0

---

src/main/java/io/phdata/streamliner/schemadefiner/configbuilder/SchemaCommand.java
src/main/java/io/phdata/streamliner/schemadefiner/configbuilder/ScriptCommand.java
src/main/java/io/phdata/streamliner/schemadefiner/util/StreamlinerUtil.java
src/main/scala/io/phdata/streamliner/App.scala
src/main/scala/io/phdata/streamliner/Cli.scala
src/test/java/io/phdata/streamliner/schemadefiner/util/StreamlinerUtilTest.java

* log4j.properties file was not loading in the artifact.
* we have added "PropertyConfigurator.configure()" to load the log4j.properties file
* added an optional parameter --log-level in schema and scripts command to set the log level
* added Junit for setting the log level

STREAM-118 Log level not changing in the streamliner artifact.

---

customer-docs/changelog.md
customer-docs/doc-versions.yml
customer-docs/user-manual.md
src/main/scala/io/phdata/streamliner/Cli.scala

* added change log for streamliner 5.7.0
* updated customer docs.

STREAM-119 Update customer docs for streamliner 5.7.0

---

customer-docs/changelog.md
customer-docs/doc-versions.yml
customer-docs/user-manual.md

This also includes STREAM-124 Document steps to connect streamliner with impala

STREAM-126 Update changelog for streamliner 4.4

---

src/main/java/io/phdata/streamliner/schemadefiner/attributeretriever/AttributeRetriever.java
src/main/java/io/phdata/streamliner/schemadefiner/attributeretriever/AttributeRetrieverFactory.java
src/main/java/io/phdata/streamliner/schemadefiner/attributeretriever/HiveAttributeRetriever.java
src/main/java/io/phdata/streamliner/schemadefiner/attributeretriever/NoOpAttributeRetriever.java
src/main/java/io/phdata/streamliner/schemadefiner/configbuilder/SchemaCommand.java
src/main/java/io/phdata/streamliner/schemadefiner/mapper/CatalogMapper.java
src/main/java/io/phdata/streamliner/schemadefiner/mapper/SnowflakeMapper.java
src/main/java/io/phdata/streamliner/schemadefiner/util/StreamlinerUtil.java

Also re-structured existing code related to source as jdbc type and destination as snowflake.
In the existing coode most of the code was using static methods and never changing fields were passed to methods to access it.
Now made them non-static and made constant fields as class level parameter so that any method can access it.
This also helped to get Jdbc and Connection details in HiveAttributeRetriever.

WIP - STREAM-128 fetch location and fileType info for hive tables

---

gradle/dependencies.gradle

* OpenCSV 5.5.2 has vulnerable common-text:1.9
* OpenCSV 5.7.1 has common-text:1.10.0

TOOL-5681 Update OpenCSV version to 5.7.1
